import { Injectable, BadRequestException } from '@nestjs/common';
import { BuyGroupsRepository } from '../interfaces/buy-groups-repository.interface';
import { PrismaService } from '../../prisma/prisma.service';
import { JoinGroupDto } from '../dto/join-group.dto';
import { MercadoPagoService } from './mercado-pago.service';
import * as crypto from 'crypto';

@Injectable()
export class PrismaBuyGroupsRepository implements BuyGroupsRepository {
  constructor(
    private readonly prisma: PrismaService,
    private readonly mercadoPago: MercadoPagoService,
  ) { }

  async getActiveGroups(nodeId: string): Promise<any> {
    const groups = await this.prisma.buy_groups.findMany({
      where: {
        node_id: nodeId,
        status: 'OPEN',
        expires_at: { gt: new Date() },
      },
      include: {
        productos: true,
        group_orders: {
          select: {
            quantity: true,
            status: true,
          },
        },
      },
    });

    return groups.map((group) => {
      const activeOrders = group.group_orders.filter(
        (o) => o.status !== 'CANCELLED',
      );
      const gathered = activeOrders.reduce(
        (sum, order) => sum + (order.quantity || 0),
        0,
      );
      const unitsLeft = Math.max(0, group.target_size - gathered);

      return {
        id: group.id,
        productId: group.product_id,
        nodeId: group.node_id,
        status: group.status,
        targetSize: group.target_size,
        createdAt: group.created_at,
        closedAt: group.closed_at,
        product: {
          id: group.productos.id,
          name: group.productos.name,
          description: group.productos.description,
          price: group.productos.price,
          bulk_size: group.productos.bulk_size,
          image_url: group.productos.image_url,
          retail_price: group.productos.retail_price,
        },
        unitsBought: gathered,
        unitsLeft: unitsLeft,
        progress:
          group.target_size > 0 ? (gathered / group.target_size) * 100 : 0,
      };
    });
  }

  async joinOrCreateGroup(userId: string, dto: JoinGroupDto): Promise<any> {
    // 1. Fetch product, node, and active group in parallel
    const [product, node, activeGroup] = await Promise.all([
      this.prisma.productos.findUnique({
        where: { id: dto.productId },
        select: { price: true, bulk_size: true },
      }),
      this.prisma.nodos.findUnique({
        where: { id: dto.nodeId },
        select: { id: true },
      }),
      this.prisma.buy_groups.findFirst({
        where: {
          product_id: dto.productId,
          node_id: dto.nodeId,
          status: 'OPEN',
          expires_at: { gt: new Date() },
        },
        select: { id: true },
      }),
    ]);

    if (!product) {
      throw new BadRequestException('El producto no existe.');
    }

    if (!node) {
      throw new BadRequestException('El punto de retiro no existe.');
    }

    let groupId = activeGroup?.id;

    // 4. If no group exists, try to create one using an upsert-like logic to handle concurrency
    if (!groupId) {
      try {
        const newGroup = await this.prisma.buy_groups.create({
          data: {
            product_id: dto.productId,
            node_id: dto.nodeId,
            target_size: product.bulk_size,
            status: 'OPEN',
          },
          select: { id: true },
        });
        groupId = newGroup.id;
      } catch (error: any) {
        // Prisma P2002 is Unique constraint failed on the fields: (`product_id`,`node_id`) where status='OPEN' (if we had such index)
        // Let's retry fetching the group
        if (error.code === 'P2002') {
          const retryGroup = await this.prisma.buy_groups.findFirst({
            where: {
              product_id: dto.productId,
              node_id: dto.nodeId,
              status: 'OPEN',
            },
            select: { id: true },
          });

          if (!retryGroup) {
            throw new BadRequestException('Error al unirse al grupo de compra.');
          }
          groupId = retryGroup.id;
        } else {
          throw new BadRequestException(`No se pudo crear el grupo de compra: ${error.message}`);
        }
      }
    }

    if (!groupId) {
      throw new BadRequestException('No se pudo establecer el grupo de compra.');
    }

    // 5. Use the token generated by the frontend
    const cardToken = dto.paymentToken;

    // 6. Create pre-authorized payment in Mercado Pago
    // product.price is the bulk price, so we calculate per-unit price
    const unitPrice = Number(product.price) / product.bulk_size;
    const amount = Math.round(unitPrice * dto.quantity * 100) / 100; // round to 2 decimals for MP
    let paymentResult;
    try {
      paymentResult = await this.mercadoPago.createPreauthorizedPayment(
        amount,
        cardToken,
        dto.cardholderEmail,
        dto.paymentMethodId,
      );
    } catch (paymentError: any) {
      throw new BadRequestException(
        `Error al pre-autorizar el pago en Mercado Pago: ${paymentError.message}`,
      );
    }

    // Validar que el pago pre-autorizado no haya sido rechazado
    if (
      !paymentResult ||
      !paymentResult.id ||
      !['authorized', 'approved', 'pending', 'in_process'].includes(paymentResult.status)
    ) {
      throw new BadRequestException(
        `El pago fue rechazado o no pudo ser procesado por Mercado Pago. Estado: ${paymentResult?.status || 'desconocido'}.`,
      );
    }

    let newOrder;
    try {
      newOrder = await this.prisma.group_orders.create({
        data: {
          group_id: groupId,
          profile_id: userId,
          quantity: dto.quantity,
          unit_price: unitPrice,
          status: 'PAYMENT_HELD',
          payment_intent_id: paymentResult.id,
        },
      });
    } catch (error: any) {
      // Intentar cancelar el pago en MP si falla la inserción en DB para evitar cobros huerfanos
      try {
        await this.mercadoPago.cancelPayment(paymentResult.id);
      } catch (cancelErr) {
        console.error('Fallo al revertir cargo en MP tras error de base de datos:', cancelErr);
      }
      throw new BadRequestException(`No se pudo registrar tu compra: ${error.message}`);
    }

    // 6. Check if the group is now completed
    const activeOrders = await this.prisma.group_orders.findMany({
      where: {
        group_id: groupId,
        status: { not: 'CANCELLED' },
      },
      select: { quantity: true },
    });

    const totalQuantity = activeOrders.reduce((sum, o) => sum + (o.quantity || 0), 0);

    if (totalQuantity >= product.bulk_size) {
      try {
        // Obtener todos los payment_intent_id y sus IDs de orden de las órdenes en PAYMENT_HELD para capturar los fondos
        const pendingOrders = await this.prisma.group_orders.findMany({
          where: {
            group_id: groupId,
            status: 'PAYMENT_HELD',
          },
          select: { id: true, payment_intent_id: true },
        });

        // Capturar fondos de todas las órdenes en Mercado Pago de forma resiliente
        const captureResults = await Promise.allSettled(
          pendingOrders
            .filter((o) => o.payment_intent_id)
            .map(async (o) => {
              const success = await this.mercadoPago.capturePayment(o.payment_intent_id!);
              return { orderId: o.id, success };
            }),
        );

        const successfulOrderIds: string[] = [];
        const failedOrderIds: string[] = [];

        captureResults.forEach((result) => {
          if (result.status === 'fulfilled') {
            if (result.value.success) {
              successfulOrderIds.push(result.value.orderId);
            } else {
              failedOrderIds.push(result.value.orderId);
            }
          }
        });

        // Ejecutar transaccionalmente: actualizar grupo a COMPLETED, órdenes a sus respectivos estados y descontar stock
        await this.prisma.$transaction(async (tx) => {
          await tx.buy_groups.update({
            where: { id: groupId },
            data: {
              status: 'COMPLETED',
              closed_at: new Date(),
            },
          });

          if (successfulOrderIds.length > 0) {
            await tx.group_orders.updateMany({
              where: {
                id: { in: successfulOrderIds },
              },
              data: {
                status: 'CONFIRMED',
              },
            });
          }

          if (failedOrderIds.length > 0) {
            await tx.group_orders.updateMany({
              where: {
                id: { in: failedOrderIds },
              },
              data: {
                status: 'CANCELLED',
              },
            });
          }

          // Restar 1 unidad del stock del producto (1 grupo completado = 1 bulto consumido)
          await tx.productos.update({
            where: { id: dto.productId },
            data: {
              stock: { decrement: 1 },
            },
          });
        });

        // Refrescar el estado del nuevo registro para la respuesta del endpoint
        if (successfulOrderIds.includes(newOrder.id)) {
          newOrder.status = 'CONFIRMED';
        } else if (failedOrderIds.includes(newOrder.id)) {
          newOrder.status = 'CANCELLED';
        }
      } catch (updateError: any) {
        throw new BadRequestException(`No se pudo consolidar el grupo y capturar los pagos: ${updateError.message}`);
      }
    }

    return newOrder;
  }

  async getMyOrders(userId: string): Promise<any> {
    const orders = await this.prisma.group_orders.findMany({
      where: { profile_id: userId },
      orderBy: { created_at: 'desc' },
      include: {
        buy_groups: {
          include: {
            productos: {
              select: {
                id: true,
                name: true,
                price: true,
                image_url: true,
              },
            },
            nodos: {
              select: {
                id: true,
                name: true,
                address: true,
              },
            },
          },
        },
      },
    });

    return orders.map((order) => ({
      id: order.id,
      group_id: order.group_id,
      profile_id: order.profile_id,
      quantity: order.quantity,
      unit_price: order.unit_price,
      status: order.status,
      created_at: order.created_at,
      group: {
        id: order.buy_groups.id,
        status: order.buy_groups.status,
        target_size: order.buy_groups.target_size,
        product: order.buy_groups.productos,
        node: order.buy_groups.nodos,
      },
    }));
  }
}
